In [2]:
import torch

a = torch.randn(2, 3)
# b= torch.Tensor([0,1], dtype = torch.int64)
b= torch.tensor([0,1])
print(a[b])

tensor([[ 0.0366,  1.2256, -0.0100],
        [-0.0384,  0.0605,  0.5275]])


In [14]:
a = torch.tensor([True, False, True])
print(~a)  # tensor([False,  True, False])
a = ~a
a = a.to(torch.uint16)
print(a)  # tensor([0, 1, 0], dtype=torch.uint16)
scores = torch.randn(2, 3)
# print(scores.masked_fill(a == False, float('-inf')))
a = a * float('-inf')
print(a)
print(scores + a)


tensor([False,  True, False])
tensor([0, 1, 0], dtype=torch.uint16)
tensor([nan, -inf, nan])
tensor([[nan, -inf, nan],
        [nan, -inf, nan]])


In [7]:
import torch
a = torch.triu(torch.ones(3, 3), diagonal=1).bool()
print(~a)

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])
